export const footerLinks = [
  "Meta",
  "About",
  "Blog",
  "Help",
  "Api",
  "Privacy",
  "Terms",
  "Top Accounts",
  "Location",
  "Instagram Lite",
  "Threads",
  "Contact uploading and non users",
  "Meta Verified",
];
