@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTQyZTNlNWRkZWM3MzE2ZTg0YWZjNiIsImlhdCI6MTY5MzIwOTIxMiwiZXhwIjoxNjkzMjMwODEyfQ.y3pFIqjIwcMj3oHY3hUolATD80n5Ejc3ONV5EimOnNc

PUT http://localhost:3000/posts/64e42f9b5ddec7316e84b114
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "caption" : "this is my favourite genshin picture"
}

