@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTQyZTNlNWRkZWM3MzE2ZTg0YWZjNiIsImlhdCI6MTY5MzIwOTIxMiwiZXhwIjoxNjkzMjMwODEyfQ.y3pFIqjIwcMj3oHY3hUolATD80n5Ejc3ONV5EimOnNc

GET http://localhost:3000/users
